### ISSUE TITLE
Wrong feature set in SAT Scenarios

### ISSUE THREAD

**Issue by mlindauer** [coseal/aslib-r#3]
http://coseal.github.io/aslib-r/scenario-pages/SAT11-RAND/llama.htm
"The feature steps correspond to the following 115 / 115 features:"

These are not the default features we agreed on.
Bug on Homepage or in aslib-r/llama?

**Comment by larskotthoff** [comment]
Somebody forgot to update the code after the spec was updated -- parsing default feature steps was completely broken for everything :(

I've fixed this and updated the github pages, but we need to rerun all the experiments. I've also opened #4 that should be implemented before rerunning.

**Comment by berndbischl** [comment]
Do we have a test for this now so this cannot happen anymore?

**Comment by berndbischl** [comment]
Or some other "guard"? What actually happened before, sorry, travelling right now and cant really invetsigate.

**Comment by larskotthoff** [comment]
Yes, I've added a test -- see the changeset.
