### ISSUE TITLE
Undefined Column Sequence

### ISSUE THREAD

**Issue by mfeurer** [coseal/aslib-r#6]
Hi,

I was trying to do algorithm selection for machine learning data. When building a model the R interpreter makes an error. I pasted my commands as well as the output:

    feurerm@aadpool4:~/Software/R-3.2.1/bin$ ./R
    
    R version 3.2.1 (2015-06-18) -- "World-Famous Astronaut"
    Copyright (C) 2015 The R Foundation for Statistical Computing
    Platform: x86_64-unknown-linux-gnu (64-bit)
    
    R is free software and comes with ABSOLUTELY NO WARRANTY.
    You are welcome to redistribute it under certain conditions.
    Type 'license()' or 'licence()' for distribution details.
    
      Natural language support but running in an English locale
    
    R is a collaborative project with many contributors.
    Type 'contributors()' for more information and
    'citation()' on how to cite R or R packages in publications.
    
    Type 'demo()' for some demos, 'help()' for on-line help, or
    'help.start()' for an HTML browser interface to help.
    Type 'q()' to quit R.
    
    > require(llama)
    Loading required package: llama
    Loading required package: mlr
    Loading required package: BBmisc
    Loading required package: ggplot2
    Loading required package: ParamHelpers
    
    Attaching package: ‘llama’
    
    The following object is masked from ‘package:BBmisc’:
    
        normalize
    
    > library(aslib)
    > scenario = parseASScenario("/home/feurerm/mhome/projects/2015_AutoSklearn_vs_AutoWEKA/metadata/aslib_matrix/aslib/binary.classification_dense_bac_metric")
    Warning in parseASScenario("/home/feurerm/mhome/projects/2015_AutoSklearn_vs_AutoWEKA/metadata/aslib_matrix/aslib/binary.classification_dense_bac_metric") :
      No cv file exists for scenario at:
    /home/feurerm/mhome/projects/2015_AutoSklearn_vs_AutoWEKA/metadata/aslib_matrix/aslib/binary.classification_dense_bac_metric
    > ldf = convertToLlama(scenario)
    > folds = cvFolds(ldf)
    > model = classify(makeLearner("classif.J48"), folds)
    Error in `[.data.frame`(data$data[data$train[[i]], ], data$features) : 
      undefined columns selected
    > 

The R interpreter is freshly compiled and runs under Ubuntu 14.04. I tried the ASP benchmark from the ASLIB and it worked without problems.

**Comment by larskotthoff** [comment]
Hmm, sounds like this is a llama issue and you should open an issue in its repository (https://bitbucket.org/lkotthoff/llama/issues?status=new&status=open). If you send me a sample of the data that allows me to reproduce the error I'd be happy to have a look.

**Comment by mfeurer** [comment]
Please excuse me, I posted this into the wrong repository. I will send you an e-mail with the files.
